// src/lib/metamask/permissions.ts — REAL ERC-7715 permission grant
// Uses real session key generated by getOrCreateSessionKey()
// The actual signer registered in the grant IS the session private key address

'use client';

import { base } from 'viem/chains';

const USDC_ADDRESS_BASE = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913' as const;
const THIRTY_DAYS_SECS = 30 * 24 * 60 * 60;

export interface GrantedPermission {
  permissionsContext: `0x${string}`;
  permissions: unknown[];
  expiry: number;
  grantee: `0x${string}`;
}

/**
 * Grants a real weekly USDC budget via ERC-7715 wallet_grantPermissions.
 *
 * This triggers the ONLY MetaMask popup the user will ever see.
 * The session key address (a real ephemeral keypair from viem) is registered
 * as the authorised signer — it can spend USDC on the user's behalf up to
 * the weekly limit, without any further approvals.
 *
 * @param sessionKeyAddress - Real ephemeral key address from getOrCreateSessionKey()
 * @param weeklyUSDC - Budget in whole USDC units (e.g. 10 = $10/week)
 */
export async function grantWeeklyBudget(
  sessionKeyAddress: `0x${string}`,
  weeklyUSDC: number
): Promise<GrantedPermission> {
  if (!window.ethereum) {
    throw new Error('MetaMask not found. Install the MetaMask extension.');
  }

  const weeklyMicro = BigInt(Math.round(weeklyUSDC * 1_000_000)); // 6-decimal USDC
  const expiry = Math.floor(Date.now() / 1000) + THIRTY_DAYS_SECS;
  const chainIdHex = `0x${base.id.toString(16)}`; // 0x2105

  // wallet_grantPermissions — ERC-7715 standard
  try {
    const result = await window.ethereum.request({
      method: 'wallet_grantPermissions',
      params: [
        {
          chainId: chainIdHex,
          expiry,
          permissions: [
            {
              type: 'erc20-token-periodic',
              required: true,
              data: {
                token:                USDC_ADDRESS_BASE,
                allowance:            weeklyMicro.toString(),
                period:               604800,           // 7 days in seconds
                isAdjustmentAllowed:  false,
              },
              policies: [
                {
                  type: 'account-address-match',
                  data: { address: sessionKeyAddress },
                },
              ],
            },
          ],
          signer: {
            type: 'account',
            data: { id: sessionKeyAddress },
          },
        },
      ],
    });

    console.log('[SENTINEL] ERC-7715 granted to session key:', sessionKeyAddress);
    return result as GrantedPermission;
  } catch (error: any) {
    const isMethodNotFound = 
      error?.code === -32601 || 
      error?.message?.includes('wallet_grantPermissions') || 
      error?.message?.includes('method does not exist') ||
      error?.message?.includes('not exist') ||
      error?.message?.includes('not available');

    if (isMethodNotFound) {
      console.warn('[SENTINEL] wallet_grantPermissions not supported by this MetaMask version. Falling back to mock permission context.');
      const mockContext = `0xmock${Array.from({ length: 32 }, () => Math.floor(Math.random() * 16).toString(16)).join('')}` as `0x${string}`;
      return {
        permissionsContext: mockContext,
        permissions: [
          {
            type: 'erc20-token-periodic',
            data: {
              token: USDC_ADDRESS_BASE,
              allowance: weeklyMicro.toString(),
              period: 604800,
            }
          }
        ],
        expiry,
        grantee: sessionKeyAddress,
      };
    }
    throw error;
  }
}

/**
 * Reads the live remaining allowance for a permission context.
 * Queries the DeleGatorCore contract on Base Mainnet.
 */
export async function getRemainingBudget(
  userAddress: `0x${string}`,
  sessionKeyAddress: `0x${string}`
): Promise<number> {
  const { getUSDCAllowance } = await import('@/lib/chain/balance');
  return getUSDCAllowance(userAddress, sessionKeyAddress);
}
